apiVersion: apps/v1
kind: Deployment
metadata:
  name: beginner-website
spec:
  replicas: 5
  selector:
    matchLabels:
      app: beginner-website
  template:
    metadata:
      labels:
        app: beginner-website
    spec:
      containers:
        - name: beginner-website
          image: parikshitsharma22/beginner-website:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
